apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seocommand-uploads
  namespace: seocommand
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Specify a StorageClass if your cluster requires one:
  # storageClassName: standard
